import os
import csv
import json
import time
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  [%(levelname)s]  %(name)s — %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

BASE_DIR      = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INPUT_CSV     = os.path.join(BASE_DIR, "data", "emails_clean.csv")
OUTPUT_DIR    = os.path.join(BASE_DIR, "data")
OUTPUT_JSONL  = os.path.join(OUTPUT_DIR, "emails.jsonl")
OUTPUT_HEADER = os.path.join(BASE_DIR, "c_engine", "headers", "email_record.h")

COLUMNS = [
    "senderEmail",
    "receiverEmail",
    "timestamp",
    "subject",
    "content",
]

FIELD_LIMITS = {
    "senderEmail":   256,
    "receiverEmail": 512,
    "timestamp":     64,
    "subject":       512,
    "body":          65536,
}


def load_csv(filepath=INPUT_CSV):
    logger.info("Loading stuff from: %s", filepath)

    with open(filepath, mode='r', encoding='utf-8') as fh:
        reader = csv.DictReader(fh)

        missing = set(COLUMNS) - set(reader.fieldnames or [])
        if missing:
            raise ValueError(
                f"CSV is missing required columns: {missing}. "
                f"Found: {reader.fieldnames}"
            )

        rows = list(reader)

    logger.info("Got %d rows", len(rows))
    return rows


def parse_fields(raw_rows):
    parsed = []

    for idx, row in enumerate(raw_rows):
        record = {
            'senderEmail':   row.get('senderEmail', ''),
            'receiverEmail': row.get('receiverEmail', ''),
            'timestamp':     row.get('timestamp', ''),
            'subject':       row.get('subject', ''),
            'body':          row.get('content', ''),
        }
        parsed.append(record)

    logger.info("Parsed %d records", len(parsed))
    return parsed


_HEADER_TEMPLATE = """\
/*
 * email_record.h
 * Auto-generated by the Data Preparation pipeline.
 * DO NOT EDIT — regenerate by re-running the pipeline.
 *
 * This struct mirrors the JSON-Lines output so the C
 * preprocessor can deserialize each record directly.
 */

#ifndef EMAIL_RECORD_H
#define EMAIL_RECORD_H

#define MAX_SENDER_EMAIL   {senderEmail}
#define MAX_RECEIVER_EMAIL {receiverEmail}
#define MAX_TIMESTAMP      {timestamp}
#define MAX_SUBJECT        {subject}
#define MAX_BODY           {body}

typedef struct {{
    char senderEmail   [MAX_SENDER_EMAIL];
    char receiverEmail [MAX_RECEIVER_EMAIL];
    char timestamp     [MAX_TIMESTAMP];
    char subject       [MAX_SUBJECT];
    char body          [MAX_BODY];
}} EmailRecord;

#endif /* EMAIL_RECORD_H */
"""


def _ensure_output_dir():
    os.makedirs(OUTPUT_DIR, exist_ok=True)


def write_jsonl(records, filepath=OUTPUT_JSONL):
    _ensure_output_dir()

    with open(filepath, mode='w', encoding='utf-8') as fh:
        for record in records:
            fh.write(json.dumps(record, ensure_ascii=False) + '\n')

    logger.info("Wrote %d records to %s", len(records), filepath)
    return os.path.abspath(filepath)


def write_c_header(filepath=OUTPUT_HEADER):
    _ensure_output_dir()

    header_content = _HEADER_TEMPLATE.format(**FIELD_LIMITS)

    with open(filepath, mode='w', encoding='utf-8') as fh:
        fh.write(header_content)

    logger.info("Generated C header at %s", filepath)
    return os.path.abspath(filepath)


def run_pipeline(csv_path=None):
    logger.info("=" * 60)
    logger.info("  DATA INGESTION PIPELINE — START")
    logger.info("=" * 60)
    start = time.time()

    raw_rows = load_csv(csv_path) if csv_path else load_csv()
    records = parse_fields(raw_rows)

    jsonl_path = write_jsonl(records)
    header_path = write_c_header()

    elapsed = time.time() - start
    logger.info("=" * 60)
    logger.info("  Done! (%.2f s)", elapsed)
    logger.info("  JSONL  → %s", jsonl_path)
    logger.info("  Header → %s", header_path)
    logger.info("  Total records: %d", len(records))
    logger.info("=" * 60)


if __name__ == '__main__':
    run_pipeline()
